#!/bin/bash
################################################################################
# Filename :   makeconfigure
# Author   :   Lovelace Lee
# Version  :   1.2.2
# Date     :   2014-5-23
# BriefInfo:   
#   makefile配置工具，详细信息参见readme
#   修改记录：
#   INCS手动添加功能 2013.10.14
#   LIBS手动添加功能 2013.10.14
#   手动配置-g -Werror选项,有-g选项时,不strip 2013.12.12
#   缺点:不支持包含空格的路径
################################################################################

function print_help()
{
    echo ""
    echo "Usage:  makeconfigure [args...]"
    echo "        (PROJECT_NAME=main):                 default [main]"
    echo "        (CROSS_COMPILER=arm-linux-):         default []"
    echo "        (INSTALL=/usr/loca/bin):             default [./bin]"    
    echo "        (PROJECT_TYPE=c|c++):                default [c]"
    echo "        (CXX|cxx):                           c++ project"
    echo "        (C|c):                               c project"
    
    echo "        (-help|--help):                      show help information"
    echo "        (-exec|-liba|-libso):                default [-exec]"
    echo "        (-publish):                          c project"
    echo "        (-I\"path\"):                        Add one include path. "
    echo "        (-L\"path\"):                        Add one lib path."
    echo "        (-DDEFINITION):                      Add one macro definition."
    echo "        (-lLIBNAME):                         Add one lib link option."
    echo ""
}

#parse ARGS
#$* all args list passed by user
function parseARGS()
{
    for arg in $*
    do
    #two arg type -arg or arg=value
        lvalue=`echo $arg | sed 's/=.*//g'`
        rvalue=`echo $arg | sed 's/.*=//g'`
        if [ -n "$arg" ];then #arg exist
            case $lvalue in
            -help|--help|--h|--he|--hel-h|-he|-hel) 
                print_help
                exit 0;;
            -publish)
                PUB_RELEASE=Y;;
            -exec)
                BUILDING_TYPE=exec;;
            -libso)
                BUILDING_TYPE=libso;;
            -liba)
                BUILDING_TYPE=liba;;
            C++|c++|cpp|CPP|Cpp|cPP|Cxx|cxx|CXX|cXX)
                PROJECT_TYPE="c++";;
            C|c)
                PROJECT_TYPE="c";;
            PROJECT_TYPE)
                case $rvalue in
                    C|c) 
                    PROJECT_TYPE="c";;
                    C++|c++|cpp|CPP|Cpp|cPP|Cxx|cxx|CXX|cXX)
                    PROJECT_TYPE="c++"
                esac;;
            PROJECT_NAME)
                PROJECT_NAME=$rvalue;;
            CROSS_COMPILER) 
                CROSS_COMPILER=$rvalue;;
            INSTALL)
                INSTALL_DIR=$rvalue;;
            -Werror|-g|-std) #支持的配置项
                m_a_k_e_o_p_t_i_o_n=._._.;;
            *) 
                arg=${lvalue:0:2}
                case $arg in
                    -I|-l|-D|-L) 
                    d_e_f_i_n_i_t_i_o_n=d_o_e_n_d
                    ;;
                    *) 
                    echo "Unknown option $lvalue"
                    return 110
                    ;;
                esac
            esac
        fi
    done
}
#查找stdfun
stdfun=/usr/local/bin/lovelacelee/stdfun
if [[ ! -e ${stdfun} ]];then
    echo "Can not find stdfun, please reinstall configure tool."
    exit 1;
else
    . $stdfun
fi
#解析配置参数,先于其他动作
parseARGS $*;
if [ $? == 110 ];then
    #need help
    print_help
    exit 1;
fi

#检测空工程
isnullproject $PROJECT_DIR;
if [ $? == 4 ];then
    echo "Project is null, without any source code file."
    exit 1;
fi

echo ""
echo "Configuring start ..."
#配置编译器
if [ -n $CROSS_COMPILER ];then
    CC=$CROSS_COMPILER$CC
    echo "Set C compiler to $CC"
    CXX=$CROSS_COMPILER$CXX
    echo "Set C++ compiler to $CXX"
    AR=$CROSS_COMPILER$AR
    echo "Set AR to $AR"
    STRIP=$CROSS_COMPILER$STRIP
    echo "Set STRIP to $STRIP"
fi
echo "Set project type to \"$PROJECT_TYPE\""
echo "Set publish release? \"$PUB_RELEASE\""
echo "Set building type to \"$BUILDING_TYPE\""
echo "Set project name to \"$PROJECT_NAME\""
echo "Set install directory to \"$INSTALL_DIR\""
#参数中读取包含的头文件目录
for arg in $*
do
    if [ -n "$arg" ];then
        if [[ ${arg:0:2} == "-I" ]];then
            incpath=${arg#*I}
            INCS=-I\"$incpath\"\ $INCS
        fi
    fi
done
echo "Set include path as \"$INCS\""
#从参数中读取包含的库链接目录
for arg in $*
do
    if [ -n "$arg" ];then
        if [[ ${arg:0:2} == "-L" ]];then
            libpath=${arg#*L}
            LIBS=-L\"$libpath\"\ $LIBS
        fi
    fi
done
echo "Set lib link path as \"$LIBS\""
#从参数中读取预定义选项-D选项
for arg in $*
do
    if [ -n "$arg" ];then
        if [[ ${arg:0:2} == "-D" ]];then
            DEFS=$arg\ $DEFS
        fi
    fi
done
echo "Set precompile defines as \"$DEFS\""
#从参数中读取链接库选项，-l选项
for arg in $*
do
    if [ -n "$arg" ];then
        case $arg in
        -liba|-libso)
            donothing=doend
            ;;
        *)
            if [[ ${arg:0:2} == "-l" ]];then
                LDFLAGS=$arg\ $LDFLAGS
            fi
            ;;
        esac
    fi
done
echo "Set linker flags as \"$LDFLAGS\""
#从参数中读取编译选项，make参数
for arg in $*
do
    lvalue=`echo $arg | sed 's/=.*//g'`
    rvalue=`echo $arg | sed 's/.*=//g'`
    if [ -n "$arg" ];then
        case $arg in
            -Werror)
                CCFLAGS=$CCFLAGS\ $arg
                CXXFLAGS=$CXXFLAGS\ $arg
            ;;
            -g)
                CCFLAGS=$CCFLAGS\ $arg
                CXXFLAGS=$CXXFLAGS\ $arg
                LDFLAGS=$LDFLAGS\ $arg
                USESTRIP=N
            ;;
        esac
        case $lvalue in
            -std)
                echo "Use -std=c99 -std=gnu99"
                CCFLAGS=$CCFLAGS\ -std=$rvalue
                CXXFLAGS=$CXXFLAGS\ -std=$rvalue
            ;; 
        esac
    fi
done
echo "Set C compiler flags \"$CCFLAGS\""
echo "Set C++ compiler flags \"$CXXFLAGS\""
generatemakefile $PROJECT_TYPE $PUB_RELEASE $BUILDING_TYPE $PROJECT_NAME; 

# debug
#echo "all *.o filelist = $OBJSLIST"

echo "Configure successful. Use make to compile the project."
echo
